### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Magicode1**
Additional description as to what it is

### CODE REVIEW

**Comment by Thunder33345** [comment]
ok we should have some discussion on how this will or should work
lets get the basic one out of here what languages we should use to make this website
wait isnt @Magicode1 founder and owner therefore should have direct push/write access?

**Comment by Magicode1** [comment]
I made a new repo with my initial html and other files for a generic website.

https://github.com/Magicode1/PocketminePluginWebsiteDevs

**Comment by EdwardHamHam** [comment]
@Thunder33345 Ah yes. Indeed @Magicode1 should.

**Comment by Thunder33345** [comment]
@Magicode1 if i am begin honest we should make a org instate so that allow other to me member or moderator of it
and i advise you to select somewhere "official" and remove all other duplicate so it wont cause confusion for the public

**Comment by Magicode1** [comment]
This is an organization, it took me a while to realize it too. I sent you an invite to join it

I deleted the other Repository :)

**Comment by Thunder33345** [comment]
hm ok thanks but imo we need somewhere to plan our plans
we could open a github issue to do our planning or something
i suppose you both are communicating somewhere would be nice if i can be added there
i could do the PHP and the handler for storing files and database (if you guys are using PHP as backbone i can help)

**Comment by Magicode1** [comment]
We are using Issues to communicate. If you want to work on the PHP side of things, that would be awesome. If you run into anything you want someone's help with, make an issue

**Comment by Thunder33345** [comment]
not to communicate of help and such i mean by discussion like next step or how it should look our goals roadmap etc
without these i cannot work properly personally i am not telepathic like you both which seems to be
(judging by how swift the operation went between you both haha not funny at all)

**Comment by EdwardHamHam** [comment]
@Thunder33345 I was indeed thinking about that. I just set up a Gitter community for that. https://gitter.im/Plug-On/Lobby
You can login with your Github account. I have already invited you and @Magicode1

**Comment by Thunder33345** [comment]
yeah we should if no one rejects using gitter
why i never mention that is because i dont know if anyone would be happy to use a 3rd platform

**Pull request merged**
